# Generated by Django 3.1.3 on 2020-12-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('material', models.TextField(help_text='Enumera el material necesario', verbose_name='Material')),
                ('objetivoTecnico', models.CharField(max_length=50, verbose_name='Objetivo tecnico')),
                ('objetivoTactico', models.CharField(max_length=50, verbose_name='Objetivo tactico')),
                ('descripcion', models.TextField(help_text='Añade una descripcion', verbose_name='Material')),
                ('representacion', models.ImageField(upload_to='ejercicios', verbose_name='Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('ejercicios', models.ManyToManyField(to='principal.Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('posicionPrincipal', models.CharField(max_length=30, verbose_name='Posicion principal')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pieDominante', models.CharField(choices=[('PD', 'Pie derecho'), ('PI', 'Pie izquierdo'), ('AM', 'Ambidiestro')], default='PD', max_length=2)),
                ('entrenamientos', models.ManyToManyField(to='principal.Entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('local', models.CharField(max_length=50, verbose_name='Local')),
                ('visitante', models.CharField(max_length=50, verbose_name='Visitante')),
                ('titular', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('tirosPuerta', models.IntegerField(verbose_name='Tiros a puerta')),
                ('goles', models.IntegerField(verbose_name='Goles')),
                ('asistencias', models.IntegerField(verbose_name='Asistencias')),
                ('robosBalon', models.IntegerField(verbose_name='Robos de balon')),
                ('balonesPerdidos', models.IntegerField(verbose_name='Balones perdidos')),
                ('minutosJugados', models.IntegerField(verbose_name='Minutos jugados')),
                ('amarillas', models.IntegerField(verbose_name='Amarillas')),
                ('rojas', models.IntegerField(verbose_name='Rojas')),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Posicion')),
            ],
        ),
        migrations.CreateModel(
            name='TestCooper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('distancia', models.IntegerField(verbose_name='Distancia recorrida')),
                ('vo2max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='vo2max')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicionesSecundarias',
            field=models.ManyToManyField(to='principal.Posicion'),
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('Injustificada', 'Injustificada'), ('Justificada', 'Justificada'), ('Lesion', 'Lesion')], default='Injustificada', max_length=30)),
                ('entrenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.entrenamiento')),
                ('jugador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.jugador')),
            ],
        ),
    ]
