# Generated by Django 3.1.3 on 2020-12-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_partido_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='posicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.posicion'),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(default=0, max_length=10, verbose_name='Resultado'),
            preserve_default=False,
        ),
    ]
