# Generated by Django 3.1.3 on 2020-12-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20201216_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='entrenamientos',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='jugadores',
            field=models.ManyToManyField(to='principal.Jugador'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(help_text='Añade una descripcion', verbose_name='Descripcion'),
        ),
    ]
