# Generated by Django 3.1.3 on 2020-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20201216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='representacion',
            field=models.ImageField(upload_to='carga', verbose_name='Ejercicio'),
        ),
    ]
