# Generated by Django 3.1.3 on 2020-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20201217_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='representacion',
            field=models.ImageField(upload_to='ejercicios', verbose_name='Ejercicio'),
        ),
    ]
