# Generated by Django 3.1.4 on 2020-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20201217_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoTactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Objetivo tactico')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Objetivo tecnico')),
            ],
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='objetivoTactico',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='objetivoTecnico',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='objetivoTactico',
            field=models.ManyToManyField(to='principal.ObjetivoTactico'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='objetivoTecnico',
            field=models.ManyToManyField(to='principal.ObjetivoTecnico'),
        ),
    ]
